#!/usr/bin/env python3
# Copyright 2014 Dietrich Epp.
# This file is part of Oubliette.  Oubliette is licensed under the terms
# of the 2-clause BSD license.  For more information, see LICENSE.txt.
import os
import subprocess
import collections
os.chdir(os.path.dirname(os.path.realpath(__file__)))
Image = collections.namedtuple('Image', 'name width height')
AUTOGEN = '// This file is automatically generated.'

def program_exists(name):
    """Determine whether a program exists in the search path."""
    for path in os.environ['PATH'].split(os.path.pathsep):
        if path and os.path.exists(os.path.join(path, name)):
            return True
    return False

if program_exists('gm'):
    def image_size(path):
        info = subprocess.check_output(
            ['gm', 'identify', '-format', '%w %h', path])
        width, height = [int(x) for x in info.split()]
        return width, height
elif program_exists('sips'):
    def image_size(path):
        output = subprocess.check_output(
            ['sips', '-g', 'pixelWidth', '-g', 'pixelHeight', path])
        info = {}
        for line in output.decode('ASCII').splitlines():
            i = line.find(':')
            if i < 0:
                continue
            info[line[:i].strip()] = line[i+1:].strip()
        return int(info['pixelWidth']), int(info['pixelHeight'])
else:
    def image_size(path):
        raise Exception('No program for determining image size found.')

def scan(root):
    dirpath = os.path.join('../../data', root)
    images = []
    for fname in os.listdir(dirpath):
        if fname.startswith('.') or not fname.endswith('.png'):
            continue
        path = os.path.join(dirpath, fname)
        width, height = image_size(path)
        images.append(Image(os.path.splitext(fname)[0], width, height))
    images.sort(key=lambda x: x.name)
    return images

def run():
    categories = ['sprite', 'ui']
    allimages = [scan(c) for c in categories]
    with open('sprite_enum.hpp', 'w') as fp:
        print(AUTOGEN, file=fp)
        for category, images in zip(categories, allimages):
            print('static const int {}_COUNT = {};'
                  .format(category.upper(), len(images)), file=fp)
            print('enum class {} {{'.format(category), file=fp)
            for image in images[:-1]:
                print('    {},'.format(image.name.upper()), file=fp)
            print('    {}'.format(images[-1].name.upper()), file=fp)
            print('};', file=fp)
    with open('sprite_array.hpp', 'w') as fp:
        print(AUTOGEN, file=fp)
        for category, images in zip(categories, allimages):
            for image in images:
                print('{{ "{}/{}", 0, 0, {}, {}, {}, {} }},'
                      .format(category, image.name,
                              image.width, image.height,
                              image.width//2, image.height//2), file=fp)

run()
