// This file is automatically generated.
enum class sprite {
    ARROW,
    BOOK1,
    BOOK2,
    CHEST,
    DOOR1,
    DOOR2,
    PLAYER,
    PRIEST,
    PROFESSOR,
    SLIME1,
    SLIME2,
    WOMAN
};
