// This file is automatically generated.
enum class sprite {
    ARROW,
    BOOK1,
    BOOK2,
    CHEST,
    DOOR1,
    DOOR2,
    HEART1,
    HEART2,
    PLAYER,
    POOF1,
    POOF2,
    POOF3,
    PRIEST,
    PROFESSOR,
    SLIME1,
    SLIME2,
    WOMAN
};
