// This file is automatically generated.
static const int SPRITE_COUNT = 19;
enum class sprite {
    BOOK1,
    BOOK2,
    CHEST,
    DOOR1,
    DOOR2,
    DOOR3,
    MOUTH1,
    MOUTH2,
    PLAYER,
    POOF1,
    POOF2,
    POOF3,
    PRIEST,
    PROFESSOR,
    SHOT,
    SKULL,
    SLIME1,
    SLIME2,
    WOMAN
};
static const int UI_COUNT = 18;
enum class ui {
    ARROW,
    CROSS,
    HEART1,
    HEART2,
    NOTES,
    SPEAKER,
    TREASURE01,
    TREASURE02,
    TREASURE03,
    TREASURE11,
    TREASURE12,
    TREASURE13,
    TREASURE21,
    TREASURE22,
    TREASURE23,
    TREASURE31,
    TREASURE32,
    TREASURE33
};
